export const cardToBankMapping = {
  'Infinia': 'HDFC Bank',
  'Regalia': 'HDFC Bank',
  'SimplySave': 'HDFC Bank',
  'Platinum': 'ICICI Bank',
  'Sapphiro': 'ICICI Bank',
  'Rubyx': 'ICICI Bank',
  'SimplyCLICK': 'SBI',
  'PRIME': 'SBI',
  'ELITE': 'SBI',
  'Millenia': 'Axis Bank',
  'Magnus': 'Axis Bank',
  'Flipkart': 'Axis Bank',
  'RBL Platinum': 'RBL Bank',
  'RBL World': 'RBL Bank',
  'RBL Fun': 'RBL Bank',
  'Club Vistara Prime': 'Vistara',
  'Club Vistara First': 'Vistara',
  'Adani One': 'Adani Wilmar',
  'Adani One Plus': 'Adani Wilmar',
  'Amazon Pay': 'ICICI Bank',
  'World Safari': 'RBL Bank',
  'MRCC': 'American Express',
  'Gold Charge': 'American Express',
  'Platinum Travel': 'American Express',
  'SimplySAVE': 'SBI',
};

export type CardName = keyof typeof cardToBankMapping;

